# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mean_my_vec_c <- function(x) {
    .Call(`_GDPSamp_mean_my_vec_c`, x)
}

ss_my_c <- function(x) {
    .Call(`_GDPSamp_ss_my_c`, x)
}

sample_mu_tau_c <- function(data, z, L, nu, W, prior_mean, prior_prec) {
    .Call(`_GDPSamp_sample_mu_tau_c`, data, z, L, nu, W, prior_mean, prior_prec)
}

Mahalanobis <- function(x, center, cov) {
    .Call(`_GDPSamp_Mahalanobis`, x, center, cov)
}

dmvnorm_my <- function(x, mean, sigma, log) {
    .Call(`_GDPSamp_dmvnorm_my`, x, mean, sigma, log)
}

multi_normal <- function(data, L, mu, tau, log_prob) {
    .Call(`_GDPSamp_multi_normal`, data, L, mu, tau, log_prob)
}

sample_my <- function(prob) {
    .Call(`_GDPSamp_sample_my`, prob)
}

sample_z_c <- function(data, beta, L, mu, tau) {
    .Call(`_GDPSamp_sample_z_c`, data, beta, L, mu, tau)
}

prob <- function(data, beta, L, mu, tau) {
    .Call(`_GDPSamp_prob`, data, beta, L, mu, tau)
}

sample_mu_tau_gdp_c <- function(data1, data2, data3, data4, data5, data6, data7, data8, z1, z2, z3, z4, z5, z6, z7, z8, L, nu, W, prior_mean, prior_prec) {
    .Call(`_GDPSamp_sample_mu_tau_gdp_c`, data1, data2, data3, data4, data5, data6, data7, data8, z1, z2, z3, z4, z5, z6, z7, z8, L, nu, W, prior_mean, prior_prec)
}

log_l <- function(data, beta, z, mu, tau) {
    .Call(`_GDPSamp_log_l`, data, beta, z, mu, tau)
}

